---
version: 2
jobs:
  build:
    working_directory: ~/tika
    docker:
      - image: circleci/ruby:2.3.7
        environment:
          RAILS_ENV: test
    steps:
      - checkout
      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: tika-{{ checksum "Gemfile.lock" }}
      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: tika-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      - persist_to_workspace:
          root: '~/tika'
          paths: '*'
  test:
    working_directory: ~/tika
    docker:
      - image: circleci/ruby:2.3.7
        environment:
          RAILS_ENV: test
    steps:
      - attach_workspace:
          at: '~/tika'
      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      - run: bundle exec rspec spec
  rubocop:
    working_directory: ~/tika
    docker:
      - image: circleci/ruby:2.3.7
        environment:
          RAILS_ENV: test
    steps:
      - attach_workspace:
          at: '~/tika'
      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      - run: bundle exec rake rubocop
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - rubocop:
          requires:
            - build
    jobs:
      - build
      - test:
          requires:
            - build
      - rubocop:
          requires:
            - build
